application:
  subdomain: migpt-server
  background_task: true
  upstreams:
    - location: /
      backend: http://migpt-server:36592/

services:
  migpt-server:
    # upstream: lmk123/migpt-server:1.12.0
    image: docker.1ms.run/lmk123/migpt-server:1.12.0
    binds:
      - /lzcapp/var/data:/root/.migptgui/default/
    setup_script: |
      echo "Setting up migpt-server..."
      if [ ! -f /root/.migptgui/default/mi.json ]; then
        echo "first run: copying mi.json."
        cp /lzcapp/pkg/content/mi.json /root/.migptgui/default/mi.json
      fi
      if [ ! -f /root/.migptgui/default/.mi.json ]; then
        echo "create mi.json file soft link."
        ln -s /root/.migptgui/default/mi.json /root/.migptgui/default/.mi.json
      fi
      echo "setup complete."
